[package]
name = "sql_query_parser"
version = "0.1.0"
edition = "2021"
description = "SQL Parser using Pest"
license = "MIT"
readme = "README.md"

[dependencies]
pest = "2.7.3"
pest_derive = "2.7.3"
thiserror = "1.0"
